lines = open('bale_3d_bot.py').readlines()
with open('bale_3d_bot.py', 'w') as f:
    for line in lines[:90]: f.write(line)
    f.write("                    if f_info.get('ok'):\n")
    f.write("                        img_url = f'https://api.bale.ai/file/bot{API_TOKEN}/{f_info[\"result\"][\"file_path\"]}'\n")
    f.write("                        local_img = os.path.join(OUTPUT_DIR, f'raw_{chat_id}.jpg')\n")
    f.write("                        with open(local_img, 'wb') as f_img: f_img.write(bot.session.get(img_url).content)\n")
    f.write("                        obj_file = bot.process_with_rhetoric(local_img, chat_id)\n")
    f.write("                        if obj_file:\n")
    f.write("                            with open(obj_file, 'rb') as f_obj:\n")
    f.write("                                bot.session.post(f'{BASE_URL}/sendDocument', data={'chat_id': chat_id, 'caption': '✅ استخراج دانش سهبعدی تکمیل شد.'}, files={'document': f_obj}, timeout=180)\n")
    f.write("                        ChaosNeutralizer.atomic_flush(chat_id)\n")
    f.write("                except Exception as inner_e:\n")
    f.write("                    print(f'⚠️ اغتشاش درونی: {inner_e}')\n")
    f.write("        except Exception as e:\n")
    f.write("            wait_time = ChaosNeutralizer.get_ambiguous_delay(2)\n")
    f.write("            print(f'🔄 بازیابی سیستم: {wait_time:.1f}s')\n")
    f.write("            time.sleep(wait_time)\n")
    f.write("\nif __name__ == '__main__':\n    main_loop()\n")
